name: Deploy Python App to Azure App Service

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: "my-project-app"  # Azure 웹앱 이름으로 변경
  PYTHON_VERSION: "3.9"                         # 사용할 Python 버전
  WORKING_DIRECTORY: "./codes" # 프로젝트 경로

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Validate path
        run: ls -la ${{ env.WORKING_DIRECTORY }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
      - name: Package application
        run: |
          # 파이썬 앱 패키징 (필요한 경우)
          # 예: static 파일 수집, 환경설정 등
          echo "Packaging completed"
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: ${{ env.WORKING_DIRECTORY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production  # GitHub 환경 설정
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ${{ env.WORKING_DIRECTORY }}
          
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ${{ env.WORKING_DIRECTORY }}  # 배포할 패키지 경로
